[core]
default_agent = "OpenHandsAgent"

[llm]
model = "huggingface/meta-llama/CodeLlama-13b-Instruct-hf"
api_key = "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" # Replace with your actual API key
temperature = 0.1
max_output_tokens = 1024
